### PR TITLE
134and141

### PR DESCRIPTION
**Pull request by bretton**
Add support for 13.4 and 14.1 installations, testing to be done with build & install

### CODE REVIEW

**Comment by bretton** [comment]
Builds fine, rc1 images at 

http://depenguin.me/files/mfsbsd-13.4-RELEASE-rc1-amd64.iso

http://depenguin.me/files/mfsbsd-14.1-RELEASE-rc1-amd64.iso

**Comment by bretton** [comment]
for 13.4 test
```
wget https://depenguin.me/qa.sh
chmod +x qa.sh
./qa.sh <your ssh key url>
```

for 14.1 test
```
wget https://depenguin.me/qa2.sh
chmod +x qa2.sh
./qa2.sh <your ssh key url>
```

older links to qa.sh and qa2.sh are now invalid

**Comment by bretton** [comment]
@Subito testing appreciated

**Comment by Subito** [comment]
14.1 (`qa2.sh`) worked without a hitch. Installed and booted without Problems. 

13.4 (`qa.sh`) installed fine, but the system does not boot afterwards. I'll let you know whats happening there once I get the console attached. 

Both tested on a AX41-NVMe.

**Comment by Subito** [comment]
it seems like I can't reproduce the problem with the console attached.

**Comment by Subito** [comment]
OK, after 4 fresh installs without any problems I'm calling it working. I don't know what happend at the first try.

**Comment by bretton** [comment]
> OK, after 4 fresh installs without any problems I'm calling it working. I don't know what happend at the first try.

awesome thanks @Subito - will try get a test myself tonight or weekend

**Comment by bretton** [comment]
I have successful install for both 13.4 and 14.1 on AX41 with HDD

**Comment by bretton** [comment]
I'll give it a couple of days for any other testing or feedback, then can go live

**Comment by Subito** [comment]
I found my error: It was completely on my side and I did not run the installer correctly. So only successfull installs from me, too.

**Comment by bretton** [comment]
images are live

**Comment by bretton** [comment]
13.4 live test is 100%, however 14.1 fails to bring up ssh. rebuilding that image and testing again

**Comment by bretton** [comment]
14.1 install with fresh image is a success. this is why we need to test the live images.

**Pull request merged**
