### PR TITLE
Add firstboot script to configure network interface

### LINKED ISSUE #75: Provide the likely interface name in the installed BSD system during the mfsBSD boot step
when the script has loaded up qemu and outputs this text
```
ssh -p 1022 mfsbsd@ip-address
```
it should also indicate the likely name of the resulting network interface in the installed system.

I don't know an easy way to do this, however I found the following
```
FreeBSD interface naming

The name of a FreeBSD interface starts with the name of its network driver.
It is then followed by a number starting at 0 that increases incrementally by
one for each additional interface sharing that driver. 
For example, a common driver used by Intel gigabit network interface cards is igb. 
The first such card in a firewall will be igb0, the second is igb1, and so on. 
Other common driver names include cxl (Chelsio 10G), em (Also Intel 1G), 
ix (Intel 10G), bge (various Broadcom chipsets), amongst numerous others.
If a system mixes an Intel card and a Chelsio card, the interfaces will be igb0
and cxl0 respectively.
```
[source](https://docs.netgate.com/pfsense/en/latest/general/interface-names.html)

It's tricky because Xneelo servers show ```eno0``` in rescue system, ```em0``` in mfsBSD, and ```igb0``` when in resulting installed FreeBSD system. 

However in some Hetzner server-bidding servers it would be ```em0``` in mfsBSD and installed FreeBSD system.

Detecting the likely result in end system, and informing user, or automatically setting, would be useful.

### PR DESCRIPTION
**Pull request by grembo**
This is pretty simple and completely untested.

Fixes depenguin-me/depenguin-run#75

### CODE REVIEW

**Comment by bretton** [comment]
include ixl0 too?

sorry not useful input, this is testing :)

I'm doing this, and updated depenguin-run wiki to reflect latest

```
git clone --recurse-submodules https://github.com/depenguin-me/depenguin-builder.git fridaytest
cd fridaytest
git fetch origin pull/19/head:fridaytest
git checkout fridaytest

# copy existing files shortcut

cp ~/settings.sh .
cp ~/FreeBSD-14.0-RELEASE-amd64-disc1.iso .

# edit build.sh

MYRELEASE="14.0-RELEASE-rc1"

./build.sh -u 14.0
```

uploads keep dying, even with rsync, will keep trying.

**Comment by bretton** [comment]
this isn't working as expected, the uploaded filename is ```14.0``` and not ```mfsbsd-14.0-RELEASE-rc1-amd64.iso```
```
rsync -P -e ssh "$OUTISO" "$CFG_SSH_REMOTEHOST":"$CFG_SSH_REMOTEPATH"/"$1"
```

it needs to be
```
rsync -P -e ssh "$OUTISO" "$CFG_SSH_REMOTEHOST":"$CFG_SSH_REMOTEPATH"/"$OUTISO"
```

**Comment by grembo** [comment]
@bretton Unrelated to this change though, isn't it?

**Comment by bretton** [comment]
I've updated the link in the qa.sh script for testing, but testers can also do:

```
wget https://depenguin.me/run.sh
chmod +x run.sh
./run.sh -m https://depenguin.me/files/mfsbsd-14.0-RELEASE-rc1-amd64.iso https://example.org/mypubkey
```

**Comment by grembo** [comment]
Really curious if this will work out of the box without any fixes (seems unlikely) :)

**Comment by bretton** [comment]
> Really curious if this will work out of the box without any fixes (seems unlikely) :)

```
/tmp/installscript: cannot create /usr/local/etc/rc.d/firstboot_depenguin: No such file or directory
```
needs this?
```
mkdir -p /usr/local/etc/rc.d/ 
```

**Comment by bretton** [comment]
ninja edited directory creation, and notice installer doesn't automatically exit mfsbsd when done. it should shut off

```
DEBUG: Installation Completed at Fri Jan  5 18:49:32 UTC 2024
```

had to shut it down manually. waiting to see if it boots and reachable

**Comment by bretton** [comment]
not coming up, requested remote console, will see what error is when I get it

**Comment by grembo** [comment]
> not coming up, requested remote console, will see what error is when I get it

It might take a while to come up though (as this is done quite late in the process, so it's not fixing the problem as early as it could).

**Comment by grembo** [comment]
In case you can log into the host, check /var/log/messages and /etc/rc.conf.

**Comment by bretton** [comment]
I accidentally rebooted it before I could see what the screen error was, will try again.

testresult1

**Comment by bretton** [comment]
fresh install, boot sequence sees em0 but then same outcome, no untrusted interface. 

no console login so can't check any logs

**Comment by bretton** [comment]
we can't have these items (and some more) without the interface being named
```
sysrc ifconfig_untrusted="up"
sysrc ifconfig_untrusted_ipv6="up"
sysrc ifconfig_untrusted_aliases="inet %%ipv4%%/32 inet6 %%ipv6%%/64"
```

**Comment by bretton** [comment]
I tried moving the various affected sysrc statements identified above into the firstboot script, but not much change in outcome

```
./depenguin_bsdinstall.sh
...
DEBUG: sysrc.subr: Successfully loaded.
sendmail_enable: NONE -> NONE
/home/user/.ssh/authorized_keys                    1712  B  737 kBps    00s
DEBUG: dialog.subr: DEBUG_SELF_INITIALIZE=[]
DEBUG: UNAME_S=[FreeBSD] UNAME_P=[amd64] UNAME_R=[14.0-RELEASE]
DEBUG: common.subr: Successfully loaded.
DEBUG: f_debug_init: ARGV=[entropy] GETOPTS_STDARGS=[dD:]
DEBUG: f_debug_init: debug=[1] debugFile=[]
DEBUG: Running installation step: entropy 
DEBUG: dialog.subr: DEBUG_SELF_INITIALIZE=[]
DEBUG: UNAME_S=[FreeBSD] UNAME_P=[amd64] UNAME_R=[14.0-RELEASE]
DEBUG: common.subr: Successfully loaded.
DEBUG: f_debug_init: ARGV=[umount] GETOPTS_STDARGS=[dD:]
DEBUG: f_debug_init: debug=[1] debugFile=[]
DEBUG: Running installation step: umount 
DEBUG: Installation Completed at Fri Jan  5 21:54:52 UTC 2024
```

reboot doesn't happen either.

I exit mfsbsd with ```shutdown -p now``` and reboot the rescue console. The resulting system has no IP address info but boots. Something isn't right in the unattended INSTALLERCONFIG file but I'm not sure what.

**Comment by bretton** [comment]
tested other variations including 
```
cat > /usr/local/etc/rc.d/firstboot_depenguin<<EOF
```
and no change, the installer script just ends like above. 

restoring host to state for other stuff, can continue with this later.

**Comment by grembo** [comment]
@bretton I didn't have the time to test anything, but I looked at the source of bsdinstall and found the underlying issue: Each occurrence of a shebang is treated as a place to split up the install script (this is how it separates configuration values from the script that is run afterwards):

```
split -a 2 -p '^#!.*' "$SCRIPT" $TMPDIR/bsdinstall-installscript-
```
Interestingly, only the first split-off script is actually run later in the script:

```
if [ -f $TMPDIR/bsdinstall-installscript-ab ]; then
	cp $TMPDIR/bsdinstall-installscript-ab $BSDINSTALL_CHROOT/tmp/installscript
...
```

So any additional scripts that are split off (in our case, that would be bsdinstall-installscript-ac) are ignored - this is why the shutdown command is not reached - the script ends at the cat command, since the next line starts with `!#` (and ends up in 
bsdinstall-installscript-ac, which is ignored).

This feels like a shortcoming in bsdinstall.

I will create a simple workaround. If all of this works, I'll probably create a small port for the rc script and add some parameters (it seems like this could be generally useful).

**Comment by grembo** [comment]
I created a patch to fix bsdinstall (if accepted, it will probably go into 15.0): https://reviews.freebsd.org/D43350

**Comment by bretton** [comment]
I can do some testing in an hour or so

**Comment by bretton** [comment]
Well done, it works! And reboots fine.

**Comment by bretton** [comment]
Should the default list be expanded?
```
${firstboot_depenguin_interfaces:="em0 igb0 bge0"}
```

I have `ixl0` on a host too.

And then some systems may have ethernet plugged into ```em1|igb1|bge1|ixl1``` for some inexplicable reason.

**Comment by grembo** [comment]
@bretton The list of interfaces to look for is configured in firstboot_depenguin_interfaces (so one could do sysrc firstboot_depenguin_interfaces="em0 ixl0" etc.) and is checked in order of definition.

The issue is, that the way it's currently done, it only looks for the existence of the interface. So if you configure em0 em1 it will always use em0.

In order to make this smarter (under the assumption the server isn't also connected to a private switch), we would have to check if the interface has a link/do some probing. This isn't particularly hard to, but will need more testing.

**Comment by grembo** [comment]
> @grembo I don't have a way of testing for em1 or similar. Lets leave that for now.
>
> happy to take live

@bretton You somehow edited my previous comment instead of replying to it :) I restored its content.

Anyway, I added some detection logic to the script now (simple), but should be good enough for most basic scenarios. If you could give it a try (I did some local tests of the script itself) that would be cool.

**Comment by bretton** [comment]
> If you could give it a try (I did some local tests of the script itself) that would be cool.

awesome thanks @grembo  that works 100%, installed fine, booted fine. manual rebooted fine.

**Comment by bretton** [comment]
works with ansible playbook too

**Pull request merged**
