### PR TITLE
Adding support for 14.2 release

### PR DESCRIPTION
**Pull request by bretton**
Adding support for 14.2 release

### CODE REVIEW

**Comment by bretton** [comment]
checksums at https://www.freebsd.org/releases/14.2R/checksums/CHECKSUM.SHA256-FreeBSD-14.2-RELEASE-amd64.asc do not match file downloaded

**Comment by bretton** [comment]
test image live at https://depenguin.me/files/mfsbsd-14.2-RELEASE-rc1-amd64.iso

and qa2.sh been updated to point to this image
```
wget https://depenguin.me/qa2.sh
chmod +x qa2.sh
./qa2.sh <your keys url>
```

**Comment by bretton** [comment]
bad image, building again

**Comment by bretton** [comment]
The step to clear disks before install `mfsbsd_clean.sh` seems to be failing due to bad inputs
```
root@mfsbsd:~ # ./mfsbsd_clean.sh zroot ada0 ada1
YOU ARE ABOUT TO DESTROY ZPOOL 'zroot' AND PARTITIONS ada0 ada1
THIS OPERATION MEANS DATA LOSS AND CANNOT BE UNDONE
Please type 'ACCEPTDATALOSS' and press enter to continue.
ACCEPTDATALOSS
cannot open 'zroot': no such pool
cannot open 'zroot': no such pool
failed to clear label for /dev/ada0p1
failed to clear label for /dev/ada0p2
failed to clear label for /dev/ada0p3
failed to open /dev/ada0p5: No such file or directory
failed to open /dev/ada0p6: No such file or directory
failed to open /dev/ada0p7: No such file or directory
failed to open /dev/ada0p8: No such file or directory
failed to open /dev/ada0p9: No such file or directory
ada0 destroyed
failed to open /dev/ada1p1: No such file or directory
failed to open /dev/ada1p2: No such file or directory
failed to open /dev/ada1p3: No such file or directory
failed to open /dev/ada1p4: No such file or directory
failed to open /dev/ada1p5: No such file or directory
failed to open /dev/ada1p6: No such file or directory
failed to open /dev/ada1p7: No such file or directory
failed to open /dev/ada1p8: No such file or directory
failed to open /dev/ada1p9: No such file or directory
gpart: arg0 'ada1': Invalid argument
DONE
```

because ada1 is showing as `diskid/DISK-QM00001`
```
root@mfsbsd:~ # gpart show
=>        40  3907029088  ada0  GPT  (1.8T)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  3889717248     4  freebsd-zfs  (1.8T)
  3907028992         136        - free -  (68K)

=>        40  3907029088  diskid/DISK-QM00001  GPT  (1.8T)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  3889717248                    4  freebsd-zfs  (1.8T)
  3907028992         136                       - free -  (68K)
```

when I run `./mfsbsd_clean.sh zroot ada0 diskid/DISK-QM00001` then it clears the disks correctly despite similar error output, and the install progresses normally without asking for zroot overwrite.

otherwise the installer pauses for input as seen here screenshot

Just to take note of, the mounted disks past ada0 might show as some other name

**Comment by bretton** [comment]
Successful install when prompt accepted, or disks correctly wiped
```
FreeBSD 14.2-RELEASE (GENERIC) releng/14.2-n269506-c8918d6c7412

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List:        https://www.FreeBSD.org/lists/questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

To change this login announcement, see motd(5).
Want to find a specific port? Just type the following under /usr/ports
or one of its subdirectories:

	make search name=<port-name>
    or
	make search key=<keyword>
```

**Comment by bretton** [comment]
do we want to consider pkgbase going forward?
https://old.reddit.com/r/freebsd/comments/1gsjbm5/installing_freebsd_with_pkgbase_november_2024/

**Comment by bretton** [comment]
@grembo @Subito testing appreciated, or ack to go ahead

**Comment by bretton** [comment]
for disk labels, spotted the following, perhaps it will help?
```
Add the following to /boot/loader.conf to make the diskid/* labels disappear forever:

​kern.geom.label.gptid.enable="0" # Disable the auto-generated GPT UUIDs for disks
```

**Comment by bretton** [comment]
no problems during manual install on 4 disk system, Intel Xeon E3-1275V6 auction server. Here is output of `gpart show`:
```
root@mfsbsd:~ # gpart show
=>        40  1875384928  ada0  GPT  (894G)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  1858072576     4  freebsd-zfs  (886G)
  1875384320         648        - free -  (324K)

=>        40  1875384928  ada1  GPT  (894G)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  1858072576     4  freebsd-zfs  (886G)
  1875384320         648        - free -  (324K)

=>        40  1875384928  ada2  GPT  (894G)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  1858072576     4  freebsd-zfs  (886G)
  1875384320         648        - free -  (324K)

=>        40  1875384928  ada3  GPT  (894G)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  1858072576     4  freebsd-zfs  (886G)
  1875384320         648        - free -  (324K)

=>        40  1875384928  diskid/DISK-QM00001  GPT  (894G)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  1858072576                    4  freebsd-zfs  (886G)
  1875384320         648                       - free -  (324K)

=>        40  1875384928  diskid/DISK-QM00002  GPT  (894G)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  1858072576                    4  freebsd-zfs  (886G)
  1875384320         648                       - free -  (324K)

=>        40  1875384928  diskid/DISK-QM00003  GPT  (894G)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  1858072576                    4  freebsd-zfs  (886G)
  1875384320         648                       - free -  (324K)

=>        40  1875384928  diskid/DISK-QM00004  GPT  (894G)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  1858072576                    4  freebsd-zfs  (886G)
  1875384320         648                       - free -  (324K)
```

output of `./mfsbsd_clean.sh zroot ada0 ada1 ada2 ada3`:
```
root@mfsbsd:~ # ./mfsbsd_clean.sh zroot ada0 ada1 ada2 ada3
YOU ARE ABOUT TO DESTROY ZPOOL 'zroot' AND PARTITIONS ada0 ada1 ada2 ada3
THIS OPERATION MEANS DATA LOSS AND CANNOT BE UNDONE
Please type 'ACCEPTDATALOSS' and press enter to continue.
ACCEPTDATALOSS
cannot open 'zroot': no such pool
cannot open 'zroot': no such pool
failed to clear label for /dev/ada0p1
failed to clear label for /dev/ada0p2
failed to clear label for /dev/ada0p3
failed to open /dev/ada0p5: No such file or directory
failed to open /dev/ada0p6: No such file or directory
failed to open /dev/ada0p7: No such file or directory
failed to open /dev/ada0p8: No such file or directory
failed to open /dev/ada0p9: No such file or directory
ada0 destroyed
failed to clear label for /dev/ada1p1
failed to clear label for /dev/ada1p2
failed to clear label for /dev/ada1p3
failed to open /dev/ada1p5: No such file or directory
failed to open /dev/ada1p6: No such file or directory
failed to open /dev/ada1p7: No such file or directory
failed to open /dev/ada1p8: No such file or directory
failed to open /dev/ada1p9: No such file or directory
ada1 destroyed
failed to clear label for /dev/ada2p1
failed to clear label for /dev/ada2p2
failed to clear label for /dev/ada2p3
failed to open /dev/ada2p5: No such file or directory
failed to open /dev/ada2p6: No such file or directory
failed to open /dev/ada2p7: No such file or directory
failed to open /dev/ada2p8: No such file or directory
failed to open /dev/ada2p9: No such file or directory
ada2 destroyed
failed to clear label for /dev/ada3p1
failed to clear label for /dev/ada3p2
failed to clear label for /dev/ada3p3
failed to open /dev/ada3p5: No such file or directory
failed to open /dev/ada3p6: No such file or directory
failed to open /dev/ada3p7: No such file or directory
failed to open /dev/ada3p8: No such file or directory
failed to open /dev/ada3p9: No such file or directory
ada3 destroyed
DONE
```

thereafter `gpart show` is empty, and install proceeds without a ZROOT exists error.

**Comment by bretton** [comment]
I'd like to take this live, however the partition labels are a concern for automation.

we need "ada0 ada1" etc, not "ada0 diskid/DISK-QM00001"

```
kern.geom.label.gptid.enable="0"
```

is already enabled. 

perhaps there's another way to do it?

It's also not consistent, works fine on one server but not another.

**Comment by grembo** [comment]
Hi @bretton,

How would I approach replicating the issue (I have only one spare test system at the moment, some EX42 or EX44)?

Cheers
Michael

**Comment by bretton** [comment]
thanks @grembo 

```
wget https://depenguin.me/qa2.sh
chmod +x qa2.sh
./qa2.sh <your keys url>
```

ssh to mfsbsd

```
gpart show
```

check if `ada0 ada1` or `ada0 diskid/DISK-QM00001`

should do the trick. I have issues with AX41 only so far.

**Comment by grembo** [comment]
@bretton This should be non-destructive, correct?
(if yes, I could test on an AX41 that is in use, but which I can take offline for a few hours)

**Comment by bretton** [comment]
@grembo yup, no need to wipe disks, just check if gpart sees the short labels for all disks

in 4 disk host, ada0 matches to diskid/DISK-QM00001, ada1 matches to diskid/DISK-QM00002, etc. 

I might be misreading the gpart output for AX41 and it's only showing ada0?

will test on ax41 again too.

**Comment by grembo** [comment]
On my AX41, I see both ada0/ada1 and diskid/DISK-QM00001 / diskid/DISK-QM00002. Note that this system already has FreeBSD installed, so both disk have complete GPT partitions. If a disk would be "raw", gpart would not show it.

When checking "zpool import", the involved devices show up with their gptid (did not actually import the pool) - which is probably good, as the underlying device names will be different once booting into the bare metal installation.

Disks are also in sysctl (as expected):

```
[root@mfsbsd /home/mfsbsd]# sysctl kern.geom.disk.ada0
kern.geom.disk.ada0.flush_notsup_succeed: 0
kern.geom.disk.ada0.flags: bc<CANDELETE,CANFLUSHCACHE,UNMAPPEDBIO,DIRECTCOMPLETION,CANZONE>
kern.geom.disk.ada0.led: 
[root@mfsbsd /home/mfsbsd]# sysctl kern.geom.disk.ada1
kern.geom.disk.ada1.flush_notsup_succeed: 0
kern.geom.disk.ada1.flags: bc<CANDELETE,CANFLUSHCACHE,UNMAPPEDBIO,DIRECTCOMPLETION,CANZONE>
kern.geom.disk.ada1.led: 
```

and in camcontrol devlist:

```
[root@mfsbsd /home/mfsbsd]# camcontrol devlist
<QEMU HARDDISK 2.5+>               at scbus0 target 0 lun 0 (pass0,ada0)
<QEMU HARDDISK 2.5+>               at scbus0 target 1 lun 0 (pass1,ada1)
<QEMU QEMU CD-ROM 2.5+>            at scbus2 target 0 lun 0 (pass2,cd0)
<QEMU QEMU CD-ROM 2.5+>            at scbus2 target 1 lun 0 (pass3,cd1)
```

I could imagine that adding `kern.geom.label.disk_ident.enable=0` to loader.conf could hide the diskid labels. *Edit: I don't think this is the right solution though - as in "it will make thinks worse"*.

AFAIK these have been there for a long time though, so I wonder what exactly causes the problems you're experiencing.

**Comment by grembo** [comment]
Wonder what the output of `geom -t` is for you

**Comment by bretton** [comment]
Awesome, thanks @grembo! 

AX41 test: all working fine this time around. Perhaps I did something wrong last time?

drives detected fine
```
Searching sd[abcd] and nvme
Detected drives: sda
sdb
Adding SATA drive: sda
Adding SATA drive: sdb
Configured disks: -drive file=/dev/sda,format=raw -drive file=/dev/sdb,format=raw
```

output of gpart show
```
gpart show
=>        40  3907029088  ada0  GPT  (1.8T)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  3889717248     4  freebsd-zfs  (1.8T)
  3907028992         136        - free -  (68K)

=>        40  3907029088  ada1  GPT  (1.8T)
          40      532480     1  efi  (260M)
      532520        1024     2  freebsd-boot  (512K)
      533544         984        - free -  (492K)
      534528    16777216     3  freebsd-swap  (8.0G)
    17311744  3889717248     4  freebsd-zfs  (1.8T)
  3907028992         136        - free -  (68K)

=>        40  3907029088  diskid/DISK-QM00001  GPT  (1.8T)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  3889717248                    4  freebsd-zfs  (1.8T)
  3907028992         136                       - free -  (68K)

=>        40  3907029088  diskid/DISK-QM00002  GPT  (1.8T)
          40      532480                    1  efi  (260M)
      532520        1024                    2  freebsd-boot  (512K)
      533544         984                       - free -  (492K)
      534528    16777216                    3  freebsd-swap  (8.0G)
    17311744  3889717248                    4  freebsd-zfs  (1.8T)
  3907028992         136                       - free -  (68K)
```

and this
```
root@mfsbsd:~ # sysctl kern.geom.disk.ada0
kern.geom.disk.ada0.flush_notsup_succeed: 0
kern.geom.disk.ada0.flags: bc<CANDELETE,CANFLUSHCACHE,UNMAPPEDBIO,DIRECTCOMPLETION,CANZONE>
kern.geom.disk.ada0.led: 

root@mfsbsd:~ # sysctl kern.geom.disk.ada1
kern.geom.disk.ada1.flush_notsup_succeed: 0
kern.geom.disk.ada1.flags: bc<CANDELETE,CANFLUSHCACHE,UNMAPPEDBIO,DIRECTCOMPLETION,CANZONE>
kern.geom.disk.ada1.led:
```

and
```
root@mfsbsd:~ # geom -t
Geom                        Class      Provider
md0                         MD         md0
  md0                       DEV       
  ffs.md0                   VFS       
  md0                       LABEL      ufsid/674ee56d2ecce02d
    ufsid/674ee56d2ecce02d  DEV       
cd0                         DISK       cd0
  cd0                       DEV       
  cd0                       LABEL      iso9660/MFSBSD
    iso9660/MFSBSD          DEV       
cd1                         DISK       cd1
  cd1                       DEV       
  cd1                       LABEL      iso9660/MFSBSD_AUTHKEYS
    iso9660/MFSBSD_AUTHKEYS DEV       
ada0                        DISK       ada0
  ada0                      DEV       
  ada0                      LABEL      diskid/DISK-QM00001
    diskid/DISK-QM00001     DEV       
ada1                        DISK       ada1
  ada1                      DEV       
  ada1                      LABEL      diskid/DISK-QM00002
    diskid/DISK-QM00002     DEV
```

**Comment by grembo** [comment]
@bretton Maybe a timing issue of some sort? For me, geom -t shows a lot more devices, by the way (maybe my manual install used a different partition scheme as you do):

ada0 for example:

```
ada0                                             DISK       ada0
  ada0                                           DEV       
  ada0                                           LABEL      diskid/DISK-QM00001
    diskid/DISK-QM00001                          DEV       
    diskid/DISK-QM00001                          PART       diskid/DISK-QM00001p1
      diskid/DISK-QM00001p1                      DEV       
    diskid/DISK-QM00001                          PART       diskid/DISK-QM00001p2
      diskid/DISK-QM00001p2                      DEV       
    diskid/DISK-QM00001                          PART       diskid/DISK-QM00001p3
      diskid/DISK-QM00001p3                      DEV       
    diskid/DISK-QM00001                          PART       diskid/DISK-QM00001p4
      diskid/DISK-QM00001p4                      DEV       
  ada0                                           PART       ada0p1
    ada0p1                                       DEV       
    ada0p1                                       LABEL      gpt/efiboot0
      gpt/efiboot0                               DEV       
    ada0p1                                       LABEL      gptid/<some uuid>
      gptid/<some uuid> DEV       
  ada0                                           PART       ada0p2
    ada0p2                                       DEV       
    ada0p2                                       LABEL      gpt/gptboot0
      gpt/gptboot0                               DEV       
    ada0p2                                       LABEL      gptid/<some uuid>
      gptid/<some uuid> DEV       
  ada0                                           PART       ada0p3
    ada0p3                                       DEV       
    ada0p3                                       LABEL      gpt/swap0
      gpt/swap0                                  DEV       
    ada0p3                                       LABEL      gptid/<some uuid>
      gptid/<some uuid> DEV       
  ada0                                           PART       ada0p4
    ada0p4                                       DEV       
    ada0p4                                       LABEL      gpt/zfs0
      gpt/zfs0                                   DEV       
    ada0p4                                       LABEL      gptid/<some uuid>
      gptid/<some uuid> DEV       
```

**Comment by bretton** [comment]
@grambo, yeah must be a funny quirk or user error, during my initial testing ada1 wasn't seen, yet is now. 

Automatic install should work fine, just completed another full install now.

Will take live, add PR for depenguin-run.

**Comment by bretton** [comment]
er, my `geom -t` might be after I'd wiped disks

**Pull request merged**
